import type { Metadata } from 'next'
import './globals.css'
import Header2 from '@/components/Header2'
import { Footer } from '@/components/Footer'

export const metadata: Metadata = {
  title: 'Amazoft',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" className="dark">
      <body className={`flex min-h-screen flex-col antialiased`}>
        <Header2 />
        <main className="flex flex-grow">{children}</main>
        <Footer />
      </body>
    </html>
  )
}
